version: '3.8'

services:

  postgres:
    image: postgres:17
    container_name: store-postgres-order-service
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: order-service:latest
    container_name: store-app-order-service
    restart: on-failure
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
       postgres:
         condition: service_healthy


volumes:
  postgres_data: