spring.config.activate.on-profile=docker

spring.datasource.url= ${DOCKER_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
user.service.url=${DOCKER_USER_SERVICE_URL}

spring.kafka.bootstrap-servers=${DOCKER_SPRING_KAFKA_BOOTSTRAP_SERVERS}