spring.config.activate.on-profile=local

spring.datasource.url= ${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
user.service.url=${LOCAL_USER_SERVICE_URL}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}